module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      textColor: {
        skin: {
          black: "var(--color-black)",
          light_blue: "var(--color-light-blue)",
          blue: "var(--color-blue)",
          dark_blue: "var(--color-dark-blue)",
          light_gray: "var(--color-light-gray)",
          gray: "var(--color-gray)",
          dark_gray: "var(--color-dark-gray)",
          white: "var(--color-white)",
          red: "var(--color-red)",
          yellow: "var(--color-yellow)",
          darker: "var(--color-darker)",
          light_green: "var(--color-light-green)",
          dark_green: "var(--color-dark-green)",
        },
      },
      backgroundColor: {
        skin: {
          black: "var(--color-black)",
          light_blue: "var(--color-light-blue)",
          blue: "var(--color-blue)",
          dark_blue: "var(--color-dark-blue)",
          light_gray: "var(--color-light-gray)",
          gray: "var(--color-gray)",
          dark_gray: "var(--color-dark-gray)",
          white: "var(--color-white)",
          red: "var(--color-red)",
          yellow: "var(--color-yellow)",
          darker: "var(--color-darker)",
          light_green: "var(--color-light-green)",
          dark_green: "var(--color-dark-green)",
        },
      },
      borderColor: {
        skin: {
          black: "var(--color-black)",
          light_blue: "var(--color-light-blue)",
          blue: "var(--color-blue)",
          dark_blue: "var(--color-dark-blue)",
          light_gray: "var(--color-light-gray)",
          gray: "var(--color-gray)",
          dark_gray: "var(--color-dark-gray)",
          white: "var(--color-white)",
          red: "var(--color-red)",
          yellow: "var(--color-yellow)",
          darker: "var(--color-darker)",
          light_green: "var(--color-light-green)",
          dark_green: "var(--color-dark-green)",
        },
      },
      ringColor: {
        skin: {
          black: "var(--color-black)",
          light_blue: "var(--color-light-blue)",
          blue: "var(--color-blue)",
          dark_blue: "var(--color-dark-blue)",
          light_gray: "var(--color-light-gray)",
          gray: "var(--color-gray)",
          dark_gray: "var(--color-dark-gray)",
          white: "var(--color-white)",
          red: "var(--color-red)",
          yellow: "var(--color-yellow)",
          darker: "var(--color-darker)",
          light_green: "var(--color-light-green)",
          dark_green: "var(--color-dark-green)",
        },
      },
    },
    minHeight: {
      20: "5rem",
    },
  },
  plugins: [],
};
